### ISSUE TITLE
Unable to type "spe" in JEI without crashing

### ISSUE THREAD

**Issue by NexusNovaz** [NFINIT-Development/mystical-skies#11]
As it says in the title. "The game crashed whilst saving entity nbt
The game crashed whilst saving entity nbt
Error: java.lang.NullPointerException: Saving entity NBT"

![image](https://user-images.githubusercontent.com/19374500/54479972-f0559180-481a-11e9-8b14-194f75852d45.png)

**Comment by knoxhack** [comment]
I need the crash-report file

**Comment by NexusNovaz** [comment]
[crash-2019-03-16_23.55.15-client.txt](https://github.com/NFINIT-Development/mystical-skies/files/2975108/crash-2019-03-16_23.55.15-client.txt)

**Comment by metalim** [comment]
No longer crashes in 0.2.1
