### ISSUE TITLE
JourneyMap data bundled with pack

### ISSUE THREAD

**Issue by metalim** [NFINIT-Development/mystical-skies#23]
some death point:
![](https://puu.sh/D42Xt/6bb919fca0.png)

near my island:
![](https://puu.sh/D429z/71fe65634e.png)

MP:
![](https://puu.sh/D437B/f49fa44233.png)

SP:
![](https://puu.sh/D438v/f3df0102b2.png)

**Comment by knoxhack** [comment]
Fixed
