### ISSUE TITLE
Crafting station slab is tricky to get due to recipe conflicts.

### ISSUE THREAD

**Issue by metalim** [NFINIT-Development/mystical-skies#24]
Those recipes do not work:
![](https://puu.sh/D43sp/b3d37442b8.png)
![](https://puu.sh/D43tx/2e2326f96b.png)

But this works:
![](https://puu.sh/D43ut/93d08b4b99.png)
![](https://puu.sh/D43uS/215164b5ab.png)

**Comment by knoxhack** [comment]
Fixed
