### ISSUE TITLE
"Virtual" diamonds?

### ISSUE THREAD

**Issue by metalim** [NFINIT-Development/mystical-skies#30]
v0.3.3

After crafting anything in crafting station, I get 64 virtual diamonds in output slot. Not craftable though.

![](https://puu.sh/D5ZgZ/37f2536bef.png)

Station is connected to Hungry Iron Chest and all other TiC tables.
UPDATE: the last doesn't matter. Bug appears in standalone Crafting Station as well.

**Comment by knoxhack** [comment]
this a thin
