### ISSUE TITLE
Hearth Well 'Book of the Well' recipe cannot be accessed via JEI.

### ISSUE THREAD

**Issue by HalcyonLioness** [NFINIT-Development/mystical-skies#36]
Just looking to see if making copies of the guidebooks was possible before jamming them into the Akashic Tome, and I found--to some mild alarm--that the recipe for 'Book of the Well' doesn't show. Instead, the recipes for 'Book of Natural Aura' and the 'Soulus' guidebook pop up in the place where the proper recipe should be.

This is admittedly a minor, negligible bug, and can be safely ignored for the most part (as it's likely not meant to be crafted in the first place!) ... but the lack of recipe for the book may affect some of the experience for those who stumble upon it. 

I hope this helps in some small way. Thank you in advance for your consideration.

![2019-03-28_01 12 35](https://user-images.githubusercontent.com/2949966/55141003-a01ddf80-50f6-11e9-808e-606e8cdd37cd.png)
.

**Comment by knoxhack** [comment]
Fixed in 1.2.0
