### ISSUE TITLE
Impossible to craft "Crafting Table"

### ISSUE THREAD

**Issue by Lorexe** [NFINIT-Development/mystical-skies#38]
Modpack Version : 1.1.1

Problem : 
We can't craft "Crafting Slab" with 4 slabs because Quark override with his own craft for "Carved Oak Wood"

Craft for Craft Slab : http://prntscr.com/n4ub8x
Craft for Carved Wood : http://prntscr.com/n4ubvd

Solution : 
- Change the craft of one of the block
- Add a mod like [NoMoreRecipeConflict](https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict)

**Comment by knoxhack** [comment]
Fixed in 1.2.0
