### ISSUE TITLE
Nether bug?!

### ISSUE THREAD

**Issue by Sa-kai** [NFINIT-Development/mystical-skies#39]
this start happening after i broke one of the chance cubes in nether.
also,some effect tryed to apply to me(i saw particle coming towards me).

![andjpg](https://user-images.githubusercontent.com/49068691/55336369-175bc680-549d-11e9-9086-5edc739544db.jpg)

**Comment by knoxhack** [comment]
Please provide the bug report file

**Comment by Sa-kai** [comment]
https://paste.dimdev.org/sadapenixi.mccrash

**Comment by knoxhack** [comment]
This inst happening anymore in recent versions right?
