### ISSUE TITLE
random hits

### ISSUE THREAD

**Issue by Sa-kai** [NFINIT-Development/mystical-skies#40]
I'm getting random hits(they do damage) when i have full saturation.started happening after i defeat first Gaia.
i thought it was thaumcraft related,so i crafted a purifying bath salt and get my self a Warp Ward,tryed to eat again,and get hits back.

**Comment by Sa-kai** [comment]
about random hits,it only happends after Gaia fight,wont stop untill i die and respawn.
Now i aslo crash from server,when ever i try to respawn.
![crashes after death](https://user-images.githubusercontent.com/49068691/55349515-33219580-54ba-11e9-81b1-8cd1da44d8a6.jpg)

**Comment by knoxhack** [comment]
Please provide the bug report file

**Comment by Sa-kai** [comment]
https://paste.dimdev.org/cipozinuxu.mccrash

**Comment by Sa-kai** [comment]
https://paste.dimdev.org/fazovunipe.mccrash
(another one)

**Comment by Sa-kai** [comment]
https://paste.dimdev.org/esenixajeb.mccrash
(from Gaia fight)
(constant damage also)

**Comment by knoxhack** [comment]
Try on next version: 1.3.2
Next time keep report and crash reports on separated pots for each one. Thanks
