### ISSUE TITLE
MultiBlock

### ISSUE THREAD

**Issue by Aliloubaba** [NFINIT-Development/mystical-skies#45]
Some Multiblock structure don't appear in the book or doesn't unlock, so I can't build my recharger because i don't know how to build it, juste the big furnace work proparly,
Thanks for your attention

**Comment by knoxhack** [comment]
Make sure to check out the mod's wiki  page https://wolforcept.github.io/hearthwell/ there are some pictures there, I just added a visual guide for the Mystical Ore puller in update 1.3.2.
If ill add more including the charger in incoming updates.

**Comment by Aliloubaba** [comment]
Thanks for your help.

**Comment by knoxhack** [comment]
Added the charger to the Visual Guide in 1.4.0
