### ISSUE TITLE
Missing Recipe: Thaumcraft Vishroom

### ISSUE THREAD

**Issue by Phantasm23** [NFINIT-Development/mystical-skies#46]
**Describe the bug**
There is no recipe in JEI for creating Vishroom.  There are several recipes that use them as an ingredient.

**To Reproduce**

**Modpack (please complete the following information):**
 - Version: 1.3.1
 - Minecraft Version: 1.12.2
 - (modded) forge-14.23.5.2824

**Comment by knoxhack** [comment]
Fixed in 1.4.0
