### ISSUE TITLE
Unable to craft Ender Crystal from Ender IO

### ISSUE THREAD

**Issue by Sa-kai** [NFINIT-Development/mystical-skies#47]
**Describe the bug**
Unable to craft the Ender Crystal from Ender IO.
The recepy in the game that is provided wont work with Special Mobs mod.
Every Enderman in the game is from Special Mobs mod and not from vanilla game,wich recepy request it.

**Desktop (please complete the following information):**
 - OS: Windows

**Modpack (please complete the following information):**
 - Version: 1.3.1.

**Additional context**

**Comment by knoxhack** [comment]
Fixed in 1.4.0
