### ISSUE TITLE
dupe bug involving silent tools

### ISSUE THREAD

**Issue by dez3940** [NFINIT-Development/mystical-skies#5]
there is a dupe bug involving the silent tools work bench. can be preformed with any item used in the crafting of silent tools items ie armor and weapons you spread items out in crafting area and shit click them out then exit bench must have blue print in one of the crafting slots it is extremely easy to reproduce and we found it on accident trying to make armor

**Comment by metalim** [comment]
Could not recreate that in 0.2.1.
Silent Gear removed in 0.3.0.
Can be closed.
