### ISSUE TITLE
Uncraftable Recipe: Wither Proofer by Auraddons

### ISSUE THREAD

**Issue by Phantasm23** [NFINIT-Development/mystical-skies#51]
**Describe the bug**
The recipe require the Ritual of the Forest, which has a specific layout.  When the design is met, the tree in the center of the pattern must grow from a sapling into a tree, which triggers the ritual magic.
The Wither Proofer recipe specifies a Dark Oak Sapling.  However, the Dark Oak Sapling needs a 2x2 pattern of sapling for the tree to grow... this pattern is not possible within the design of the Ritual of the Forest's structure.  It needs to be a type of sapling that will sprout with just one sapling and is preferably none destructive to nearby terrain.

**To Reproduce**

**Expected behavior**
Once the Ritual is laid out and prepared, the sapling should grow into a tree, triggering the magic... over a short time, the surrounding items get absorbed and the created item falls to the ground as the tree vanishes.

**Screenshots**
![image](https://user-images.githubusercontent.com/6567299/55624451-14d2d700-57e5-11e9-8ac4-26c3b924f4f2.png)
![image](https://user-images.githubusercontent.com/6567299/55624496-4481df00-57e5-11e9-8b19-293681096aa9.png)

**Modpack (please complete the following information):**
 - Version: 1.4.1

**Comment by knoxhack** [comment]
https://github.com/superaxander/Auraddons/issues/5

**Comment by knoxhack** [comment]
Fixed in 1.5.0
