### ISSUE TITLE
Wrong colors on chests.

### ISSUE THREAD

**Issue by Sa-kai** [NFINIT-Development/mystical-skies#52]
**Describe the bug**
Most of the chest from Vanilla/MetalChest mod or Quark mod have yellowish collor added on top of existing one.

**Screenshots**
![color](https://user-images.githubusercontent.com/49068691/55641606-9834fe00-57ce-11e9-9371-f48d410326b3.jpg)

**Desktop (please complete the following information):**
 - OS:Windows

**Modpack (please complete the following information):**
 - Version: 1.4.1.

**Additional context**
Didnt happend before 1.4.1. update.

**Comment by knoxhack** [comment]
🤔

**Comment by Sa-kai** [comment]
i think its because od draconic evolution,if you stand in the way of paricals from energy pylons color changes to most things.
even on spabilizators (laser part) from energy core.

**Comment by knoxhack** [comment]
yeah, not a bug then
