### ISSUE TITLE
Right clicking on dirt with Mysterious Dust does not create Mystical Grass for me

### ISSUE THREAD

**Issue by xHedra** [NFINIT-Development/mystical-skies#54]
Right clicking on dirt with Mysterious Dust does not create Mystical Grass for me
Right clicking on dirt with Mysterious Dust does not create Mystical Grass for me

**Modpack (please complete the following information):**
 - Version: 1.4.2

**Comment by Sa-kai** [comment]
its not a dirt you right click with mysterious dust,bt the Grass block.

**Comment by xHedra** [comment]
Apparantly I do not know how to read. Sorry for that.

Thanks Sa-kai
