### ISSUE TITLE
Uncraftable item

### ISSUE THREAD

**Issue by Sa-kai** [NFINIT-Development/mystical-skies#57]
**Describe the bug**
an item named "P-Alloy Tactical Shears" are unable to craft.

**Screenshots**
![uncraftable](https://user-images.githubusercontent.com/49068691/55685352-4cf92780-5955-11e9-86a0-b3ce52dbfa4f.jpg)

**Desktop (please complete the following information):**
 - OS: Windows

**Modpack (please complete the following information):**
 - Version: 1.5.0.

**Comment by knoxhack** [comment]
You can only craft that item after fighting the potato boss

**Comment by MutantDragon** [comment]
I have defeated the final potato boss several times, but the shears are still not craftable.
![2019-08-01_02 09 31](https://user-images.githubusercontent.com/53559700/62280873-92100080-b401-11e9-9c2b-8311778e1efc.png)
