### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by marci747** [NFINIT-Development/mystical-skies#60]
**Describe the bug**
I become Internal Server error when i join the server i was in a nether Dungeon have loot a chest and then comes Server crash or restart and now i dont come in. 
 
Modpack: Mystical Skies version 1.5.1

That was the last item what i loot

IGN:Lordmarci87

![2019-04-10_10 20 28](https://user-images.githubusercontent.com/22216006/55863406-be65ef80-5b7a-11e9-8fc3-fb1d17919f5c.png)

**Comment by knoxhack** [comment]
Server side bug
