### ISSUE TITLE
Throwing a crystal block though a nether portal crashes the server

### ISSUE THREAD

**Issue by Psion77** [NFINIT-Development/mystical-skies#63]
The game crashes if you throw a crystal block from hearth well through the nether portal. It crashes again if you try to reload the save. Crash report here:

https://paste.dimdev.org/ehatalolox.mccrash

**Comment by Psion77** [comment]
To add to this, restarting minecraft lets me log in. The Vanilla Fix restart is not enough.

**Comment by knoxhack** [comment]
fixed in 1.7.0
