### ISSUE TITLE
Mysterious leaves do not drop

### ISSUE THREAD

**Issue by Hieronimus68** [NFINIT-Development/mystical-skies#64]
When starting a new map, following the manual, breaking the mysterious leaves with empty hands does not result in the leaves dropping.

Shears are in the questbook, now the manual has to be changed :)

Starting a new map does not solve the issue.

**Desktop (please complete the following information):**
 - OS: Windows 10 {java version}

**Modpack (please complete the following information):**
 - Version: 1.6.1
 - Version: 1.6.2

**Comment by Dephyantx** [comment]
Same Issue. Unable to begin the pack as no leaves drop from the start. Tried breaking them with an empty hand, with an item in hand and nothing. Started a new map and had the same issue.

**Comment by knoxhack** [comment]
intentional
