### ISSUE TITLE
Mystical+Skies-1.7.0-server crash-reports

### ISSUE THREAD

**Issue by along00852** [NFINIT-Development/mystical-skies#66]
Describe the bug
The "Rain Flower" from Botanic Additions causes the server to crash when it is raining.

To Reproduce
There will be problems in the world when it rains.

Desktop
 - OS:  win10

Modpack
 - Version: 1.7.0

https://github.com/along00852/Mystical-Skies-1.7.0-server-crash-reports/blob/master/crash-2019-05-03_17.47.19-server.txt

**Comment by knoxhack** [comment]
Duplicated of https://github.com/NFINIT-Development/mystical-skies/issues/50
