### ISSUE TITLE
Simple Storage Network not opening

### ISSUE THREAD

**Issue by Salnex** [NFINIT-Development/mystical-skies#68]
**Describe the bug**
Simple Storage Network GUI does not open on storage request table

**To Reproduce**
Place network controller, storage request table and attach a chest with a storage cable. Right click on storage request table.

**Expected behavior**
GUI opens

**Screenshots**
![2019-06-03_21 49 46](https://user-images.githubusercontent.com/26846378/58802194-e55b1200-864f-11e9-8d21-8db5a05eb34b.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10

**Modpack (please complete the following information):**
 - Version:  1.7.1

**Additional context**
https://paste.dimdev.org/dehosuxigu.mccrash
Despite what log may lead to believe is actually an issue with FastWorkbench. 1.7.0 introduced a new function, and storage network relies on this. Updating to 1.7.0 of FastWorkbench resolves this issue

**Comment by Salnex** [comment]
Changing B:allowFastWorkBenchIntegration=True to B:allowFastWorkBenchIntegration=false in simple storage networks also resolves

**Comment by VallenFrostweaver** [comment]
The latest version of Fast Workbench should fix this. A mod update should allow it's use again. Can we get an update pretty pls?

**Comment by Nightcaste** [comment]
This is not a "Mod Issue", because the issue is that incompatible versions of the mods were selected.  That make it a *pack* issue.
