### ISSUE TITLE
No chest

### ISSUE THREAD

**Issue by DarkPuppetier** [NFINIT-Development/mystical-skies#72]
**Describe the bug**
There is no starting chest on the island.

**To Reproduce**
Steps to reproduce the behavior: Make a new island in version 1.8

**Expected behavior**
There is no starting chest with the mystic bag and hearth well book inside.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 

**Modpack (please complete the following information):**
 - Version: 

**Additional context**

**Comment by Nightcaste** [comment]
Updating from 1.7.1 to 1.8.1 also erases every single one on a server.

**Comment by knoxhack** [comment]
Fixed in 1.8.2
