### ISSUE TITLE
Many quests locked behind "info quests"

### ISSUE THREAD

**Issue by maham** [NFINIT-Development/mystical-skies#79]
**Describe the bug**
After the 1.8.1 update the quests that show the different portal options you can't get past those to continue questing.

**To Reproduce**
Open the quest book

**Expected behavior**
Some way to complete the "info quests" to be able to progress with the questing.

**Desktop (please complete the following information):**
 - OS: Win10

**Modpack (please complete the following information):**
 - Version: 1.8.1

**Comment by knoxhack** [comment]
Fixed in 1.8.2
