### ISSUE TITLE
Crushing block

### ISSUE THREAD

**Issue by tzaddi64** [NFINIT-Development/mystical-skies#80]
When I throw an item so I can crush it with the crushing block, the item comes immediately back before I can even move the cursor to the crushing block. I have several different items and they all return before I can crush them. Version 1.81

**Comment by mkleiman312** [comment]
Sounds like you have a magnet on you? The starter pouch acts as a magnet (says so in the tooltip) and is the most likely cause. (Tinkers can also add magnetic effects to tools and armor, but its probably the pouch.)

**Comment by tzaddi64** [comment]
The pouch was it. I feel silly, cause I checked everything but the pouch.

**Comment by TylAshke** [comment]
we all have been there :-)
