### ISSUE TITLE
no way to get prosperity shards

### ISSUE THREAD

**Issue by MrBlayz** [NFINIT-Development/mystical-skies#81]
no way to get prosperity shards other than ore is wrong! you can git it thru the nether! I'm sorry for my stupidity.

**Comment by mkleiman312** [comment]
#75

**Comment by MrBlayz** [comment]
thank you

**Comment by TylAshke** [comment]
there is prosperity ore in the nether

**Comment by knoxhack** [comment]
Fixed in 1.8.2
