### ISSUE TITLE
Recipe for summoner from Solus is overwritten (you can still craft it)

### ISSUE THREAD

**Issue by Keltas** [NFINIT-Development/mystical-skies#91]
**Describe the bug**
According to JEI the only recipe for the summoner is to surround ender dust with endersteel bars. However this recipe is not working due to being overwritten by the shapeless recipe for Endersteel bars in Ender style. This results in the only style of summoner you can make being ender. It also requires an extra piece of ender dust first to craft ender styled bars and then summoner.

**To Reproduce**
Steps to reproduce the behavior: In a crafting grid put ender dust from soulus in the middle and surround it by 8 endersteel bars.

**Expected behavior**
For the shaped recipe for the summoner to overwrite the shapeless recipe for Ender style instead of the other way.

**Screenshots**
![bug](https://user-images.githubusercontent.com/6074403/61379843-f9ca3580-a8b0-11e9-800f-bfdce8ba7f46.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Modpack (please complete the following information):**
 - Version: 1.8.2

**Additional context**

**Comment by irondragon12** [comment]
I have the same problem

**Comment by knoxhack** [comment]
Fixed in 1.8.3
