### ISSUE TITLE
Crash when starting modpack : Chance Cube ?

### ISSUE THREAD

**Issue by ghost** [NFINIT-Development/mystical-skies#92]
**Describe the bug**
I'm trying to start for the first time the modpack but it is getting stuck at chance cube chargement, and keep crashing on me

**Crash Report : **
https://paste.dimdev.org/lufirekure.mccrash

**Desktop :**
 - OS: Windows

**Modpack :**
 - Version:  1.8.3

**Additional context**

**Comment by curiosity-a** [comment]
Did you even read that? You are running out of memory.
